stages:
  - test
  - build
  - deploy

services:
  - docker:dind

cache:
  paths:
    - vendor/

test:
  image: php:8.3-cli
  stage: test
  script:
    - apt-get update && apt-get install -y zlib1g-dev git libzip-dev unzip libicu-dev
    - docker-php-ext-configure intl && docker-php-ext-install intl
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/bin --filename=composer
    - composer install
    - mkdir -p temp/cache
    - mkdir -p temp/sessions
    - mkdir -p temp/data
    - mkdir -p log
    - php vendor/bin/tester -c tests/unit/php.ini tests/unit/
    - php vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=256M -l max app

build:
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  image: alpine:3.9
  stage: deploy
  script:
    - apk update
    - apk add --no-cache openssh-client ca-certificates bash
    - echo $DEPLOY_KEY | base64 -d > key
    - chmod 400 key
    - ssh -i key -oStrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_SERVER_IP} 'docker pull registry.gitlab.com/kozaktomas/personal-web:latest && cd /root/infra/vps && docker-compose stop kozak_in_php kozak_in_lb && docker-compose up -d kozak_in_php kozak_in_lb'
  only:
    - master
