stages:
  - test
  - build
  - e2e
  - deploy
  - after

services:
  - docker:dind

cache:
  paths:
    - vendor/

.e2e:
  image: docker/compose:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  artifacts:
    paths:
      - tests/e2e/cypress/videos/app.js.mp4
    expire_in: 1 week
  script:
    - docker-compose -f docker-compose-ci-e2e.yml up -d web
    - docker-compose -f docker-compose-ci-e2e.yml run e2e

test:
  image: php:8.0-cli
  stage: test
  script:
    - apt-get update && apt-get install -y zlib1g-dev git libpq-dev libzip-dev unzip libicu-dev
    - docker-php-ext-configure intl && docker-php-ext-install intl
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/bin --filename=composer
    - composer install
    - mkdir -p temp/cache
    - mkdir -p temp/sessions
    - mkdir -p temp/data
    - mkdir -p log
    - php vendor/bin/tester -c tests/unit/php.ini tests/unit/
    - php vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=256M -l max app

build:
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

e2e:
  extends: .e2e
  stage: e2e
  variables:
    APP_URL: http://web:80

deploy:
  image: alpine:3.9
  stage: deploy
  script:
    - apk update
    - apk add --no-cache openssh-client ca-certificates bash
    - echo $DEPLOY_KEY | base64 -d > key
    - chmod 400 key
    - ssh -i key -oStrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_SERVER_IP} 'docker pull registry.gitlab.com/kozaktomas/personal-web:latest && cd wedos-vps && docker-compose stop kozak_in && docker-compose up -d kozak_in'
  only:
    - master

e2e-prod:
  extends: .e2e
  stage: after
  variables:
    APP_URL: https://kozak.in
  only:
    - master