stages:
  - test
  - build
  - deploy

services:
  - docker:dind

cache:
  paths:
    - vendor/

test:
  image: php:8.4-cli
  stage: test
  script:
    - apt-get update && apt-get install -y zlib1g-dev git libzip-dev unzip libicu-dev
    - docker-php-ext-configure intl && docker-php-ext-install intl
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/bin --filename=composer
    - composer install
    - mkdir -p temp/cache
    - mkdir -p temp/sessions
    - mkdir -p temp/data
    - mkdir -p log
    - php vendor/bin/tester -c tests/unit/php.ini tests/unit/
    - php vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=256M -l max app

build:
  image: docker:stable
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
