version: '3.8'
services:
  web:
      image: ${CI_REGISTRY_IMAGE}:latest
      env_file:
        - dev.env
  redis:
      image: redis:latest
  e2e:
      image: cypress/included:3.4.0
      command: ["--env", "APP_BASE_URL=${APP_URL}"]
      working_dir: /e2e
      depends_on:
        - web
      volumes:
        - ./tests/e2e:/e2e
