version: '3'
services:
  php:
    build: docker
    volumes:
      - .:/var/www/html
      - ./data/sock:/sock
      - ./docker/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
#      - ./docker/xdebug.conf:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    env_file:
      - dev.env
      - .env
    environment:
      DEV: "true"
      PHP_IDE_CONFIG: serverName=localhost
  lb:
    image: ghcr.io/kozaktomas/gophpfpm:main
    ports:
      - "8081:8080"
    volumes:
      - ./public:/static/public
      - ./data/sock:/sock
    command:
      - "--app=personal_web"
      - "--port=8080"
      - "--socket=/sock/php-fpm.sock"
      - "--index-file=/var/www/html/app/index.php"
      - "--static-folder=/static/public:/public"
      - "--access-log"
      - "--fpm-pool-size=16"
    depends_on:
      - php
  e2e:
    image: cypress/included:10.8.0
    command: ["--env", "APP_BASE_URL=http://lb:8080"]
    working_dir: /e2e
    depends_on:
      - php
      - lb
    volumes:
      - ./tests/e2e:/e2e
