version: '3.8'
services:
  web:
      build: docker
      ports:
          - "8091:80"
      volumes:
        - .:/var/www/html
      env_file:
        - dev.env
        - .env
      environment:
        DEV: "true"
  redis:
      image: redis:latest
  e2e:
      image: cypress/included:3.4.0
      command: ["--env", "APP_BASE_URL=http://web:80"]
      working_dir: /e2e
      depends_on:
        - web
      volumes:
        - ./tests/e2e:/e2e
