version: '3.1'
services:
  web:
      build: docker
      ports:
          - "8091:80"
      volumes:
        - .:/var/www/html
      env_file:
        - dev.env
        - .env
      environment:
        DEV: "true"